blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.EntryListView.as_view(), name='list'),
    path('<slug:slug>', views.EntryDetailView.as_view(), name='details'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('send', views.send_order, name='send_order'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        '^remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views
from .admin import login_as_user

app_name = 'mysite'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='entry')),
    path('articles/', include('articles.urls', namespace='article')),
    path('products/', include('products.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('registration.backends.default.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^login/user/(?P<user_id>[\d_]+)$', login_as_user),
    path('search/', include('haystack.urls')),
]

products/urls.py
from . import views
from django.urls import path

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='details'
    ),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from .tasks import send_email
from django.template import loader


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'update': True}
        )
    return render(request, 'cart/detail.html', {'cart': cart})


def send_order(request):
    cart = Cart(request)
    if request.user.is_authenticated:
        user_email = request.user.email
        template = 'cart/email/send_order_email.html'
        text = loader.render_to_string(template, {'cart': cart, })
        send_email.delay(text, user_email)
        cart.clear()
        return render(request, 'cart/order.html')
    else:
        return render(request, 'mysite/base.html')

templates/cart/detail.html
{% extends "products/base.html" %}
{% block title %}
    Your Shopping Cart
{% endblock %}
{% block content %}
<h2>Your Shopping Cart
<br>
    <span>
        {% with totail_items=cart|length %}
            {% if cart|length > 0 %}
                My Shopping Order:
                <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                    {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </span>
</h2>
    <table>
        <thead style="background-color: #5AC8FA">
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Price</th>
            </tr>
        </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product  %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                    </td>
                    <td>kshs. {{ item.price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr style="background-color: #5AC8FA">
            <td><b>Total</b></td>
            <td colspan="2"></td>
            <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
        </tr>
        </tbody>
    </table>
<p>
    <a href="{% url 'products:list' %}">Continue Shopping</a>
    <a href="{% url 'cart:send_order' %}">Checkout</a>
</p>
{% endblock %}

templates/cart/order.html
{% extends "products/base.html" %}
{% block content %}
    <a>Thank you for buying check your e-mail</a>
{% endblock %}