blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.EntryListView.as_view(), name='list'),
    path('<slug:slug>', views.EntryDetailView.as_view(), name='details'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('send', views.send_order, name='send_order'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        '^remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views
from .admin import login_as_user

app_name = 'mysite'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='entry')),
    path('articles/', include('articles.urls', namespace='article')),
    path('products/', include('products.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('registration.backends.default.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^login/user/(?P<user_id>[\d_]+)$', login_as_user),
    path('search/', include('haystack.urls')),
]

products/urls.py
from . import views
from django.urls import path

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='details'
    ),
]

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(
        _('title'),
        max_length=255,
    )

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2
    )

    slug = models.SlugField(
        _('slug'),
        max_length=255
    )

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:details', args=[self.id, self.slug])

products/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput,
    )

products/views.py
from django.views.generic import ListView

from django.shortcuts import (
    redirect,
    render,
    get_object_or_404,
)


from .models import Product
from .forms import CartAddProductForm


class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'
    context_object_name = 'products'
    paginate_by = 10
    queryset = Product.objects.all()


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug,)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'products/detail.html', context)

templates/products/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title> {% block title %}
            {% endblock %}</title>
    </head> 
    <body>
    <a href="{% url 'cart:cart_detail' %}">my cart</a>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/products/detail.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
<div style="padding-left: 20px">
  <h3>{{ product.name }}</h3>
  <p>Kshs. {{ product.price }}</p>
  <form action="{% url "cart:cart_add" product.id %}" method="post">
      {% csrf_token %}
      {{ cart_product_form }}
      <input type="submit" value="add to cart">
  </form>
</div>
{% endblock %}

templates/products/list.html
{% extends "products/base.html" %}

{% block content %}
  {% for product in products %}
    <article>
      <header>

        <h2>
          <a href="{{ product.get_absolute_url }}" title="">{{ product.name }}</a>
          <a>{{ product.price }}</a>
        </h2>    

      </header> 

    </article>

  {% empty %}
    <h1>No products found.</h1>
  {% endfor %}

  <div>
    <span>
      {% if is_paginated %}
        <ul>
        {% if page_obj.has_previous %}
            <li>
                <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
            </li>
        {% endif %}
            <li>
                <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
            </li>
        {% if page_obj.has_next %}
            <li>
                <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
            </li>
        {% endif %}
      {% endif %}
    </span>
  </div>

{% endblock content %}