blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.EntryListView.as_view(), name='list'),
    path('<slug:slug>', views.EntryDetailView.as_view(), name='details'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views
from .admin import login_as_user

app_name = 'mysite'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='entry')),
    path('articles/', include('articles.urls', namespace='article')),
    path('products/', include('products.urls', namespace='product')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('registration.backends.default.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^login/user/(?P<user_id>[\d_]+)$', login_as_user),
    path('search/', include('haystack.urls')),
]

products/urls.py
from . import views
from django.urls import path

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='details'
    ),
]

mysite/views.py
from django.views.generic.base import TemplateView


class HomeView(TemplateView):

    template_name = "mysite/base.html"

templates/mysite/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title> {% block title %}
            {% endblock %}</title>
        {% load socialaccount %}
        {% providers_media_js %}
    </head> 
    <body>
    <a href="{% url 'article:list' %}">Articles</a>
    <a href="{% url 'blog:list' %}">Entries</a>
    <a href="{% url 'products:list' %}">Products</a>
        {% if user.is_authenticated %}
            <a href="{% url 'auth_logout' %}" style="float:right; margin-left: 5px;">Logout</a> 
            {{ user.username }}
        {% else %}
            <div>
                <a href="{% url 'auth_password_reset' %}" style="float:right; margin-left: 5px;">Reset Password</a>
                <a href="{% url 'registration_register' %}" style="float:right; margin-left: 5px;">Register </a></div>
                <a href="{% url 'auth_login' %}" style="float:right;">Login</a>
                <a href="{% provider_login_url 'facebook' method='js_sdk' %}">Login Facebook</a>
                <a href="{% provider_login_url 'twitter' %}">Sign in with Twitter</a>
            </div>
        {% endif %}
        <form action="/search" method="get" class="navbar-search pull-left">
            <input type="text" placeholder="Search" class="search-query span2" name="q">
        </form>
        {% block content %}

        {% endblock %}
    </body>
</html>